version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/mali3days/hyperbag
    
    steps:
      - checkout
      - attach_workspace:
          at:  ~/mali3days/hyperbag
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist


workflows:
  version: 2
  build:
    jobs:
      - build